/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emitcsa.Vistas;

/**
 *
 * @author Eliezer
 */
public class vista1 extends javax.swing.JFrame {

    /**
     * Creates new form vista1
     */
    public vista1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        edoo = new javax.swing.JLabel();
        jla1 = new javax.swing.JLabel();
        btnDatos = new javax.swing.JLabel();
        btnDB = new javax.swing.JLabel();
        jla3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(153, 0, 0));
        jPanel3.setLayout(null);

        edoo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edooMouseClicked(evt);
            }
        });
        jPanel3.add(edoo);
        edoo.setBounds(0, 860, 110, 110);

        jla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jla1MouseClicked(evt);
            }
        });
        jPanel3.add(jla1);
        jla1.setBounds(480, 70, 440, 410);

        btnDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDatosMouseClicked(evt);
            }
        });
        jPanel3.add(btnDatos);
        btnDatos.setBounds(1460, 70, 440, 410);

        btnDB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDBMouseClicked(evt);
            }
        });
        jPanel3.add(btnDB);
        btnDB.setBounds(970, 530, 440, 430);

        jla3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jla3MouseClicked(evt);
            }
        });
        jPanel3.add(jla3);
        jla3.setBounds(970, 70, 440, 410);

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2);
        jLabel2.setBounds(480, 520, 440, 420);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emitcsa/imagen/Inicio.png"))); // NOI18N
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edooMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edooMouseClicked


System.exit(WIDTH);
    }//GEN-LAST:event_edooMouseClicked

    private void jla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jla1MouseClicked
        vista2 v2 = new vista2();
        v2.setVisible(true);
        
        this.setVisible(false);

    }//GEN-LAST:event_jla1MouseClicked

    private void btnDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDatosMouseClicked
        // TODO add your handling code here:
       vista7 v7 = new vista7();
        v7.setVisible(true);
        
        this.setVisible(false);
        //aaaaa
    }//GEN-LAST:event_btnDatosMouseClicked

    private void btnDBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDBMouseClicked
        // TODO add your handling code here:
        vista4 v4 = new vista4();
        v4.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_btnDBMouseClicked

    private void jla3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jla3MouseClicked
        // TODO add your handling code here:
        vista3 v3 = new vista3();
        v3.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jla3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        vista8 v8 = new vista8();
        
        v8.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDB;
    private javax.swing.JLabel btnDatos;
    private javax.swing.JLabel edoo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jla1;
    private javax.swing.JLabel jla3;
    // End of variables declaration//GEN-END:variables
}
